"""Training script for supervised fine-tuning using LoRA/QLoRA.

This module wraps the HuggingFace/PEFT/TRL machinery to take the preprocessed
JSONL files generated by ``llm_pipeline_preprocess.py`` and apply LoRA or
QLoRA adapters to a base causal language model.

Features:

* Choice of base model from the HuggingFace hub.
* Toggle between ``lora`` (full-precision adapter) and ``qlora``
  (4-bit quant + LoRA) with ``--lora_type``.
* Configurable hyperparameters such as learning rate, batch size, epochs.
* Saves both the adapter weights and tokenizer to ``--output_dir``.

The script is intentionally minimal and easy to read so that students can
understand each step - comments are sprinkled throughout.

Example::

    python llm_pipeline_train.py \
        --model_name gpt2 \
        --data_dir training_data \
        --output_dir artifacts/my-adapter \
        --lora_type qlora

"""

import argparse
from pathlib import Path

import torch
from datasets import load_dataset
from peft import LoraConfig
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from trl import SFTConfig, SFTTrainer


def main() -> None:
    parser = argparse.ArgumentParser(description="LoRA/QLoRA fine-tuning pipeline")
    parser.add_argument("--model_name", default="TinyLlama/TinyLlama-1.1B-Chat-v1.0",
                        help="Hugging Face model identifier to use as base")
    parser.add_argument("--data_dir", default="training_data",
                        help="Directory containing train/val JSONL files")
    parser.add_argument("--output_dir", default="artifacts/adapter",
                        help="Where to save resulting adapter and tokenizer")
    parser.add_argument("--epochs", type=int, default=3,
                        help="Number of training epochs")
    parser.add_argument("--lr", type=float, default=2e-4,
                        help="Learning rate for optimizer")
    parser.add_argument("--batch_size", type=int, default=2,
                        help="Per-device batch size")
    parser.add_argument("--lora_type", choices=["lora", "qlora"],
                        default="qlora",
                        help="Whether to run plain LoRA or QLoRA (quantized)")
    args = parser.parse_args()

    # prepare dataset
    data_dir = Path(args.data_dir)
    dataset = load_dataset(
        "json",
        data_files={
            "train": str(data_dir / "train.jsonl"),
            "validation": str(data_dir / "val.jsonl"),
        },
    )

    # tokenizer setup
    tokenizer = AutoTokenizer.from_pretrained(args.model_name, use_fast=True)
    if tokenizer.pad_token is None:
        # causal models often lack a pad token; set it to eos for batching
        tokenizer.pad_token = tokenizer.eos_token

    # model loading
    if args.lora_type == "qlora":
        # QLoRA uses 4-bit quantization to reduce memory footprint.
        # ``BitsAndBytesConfig`` configures the quantization scheme.
        bnb_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=torch.float16,
            bnb_4bit_use_double_quant=True,
        )
        model = AutoModelForCausalLM.from_pretrained(
            args.model_name,
            quantization_config=bnb_config,
            device_map="auto",
        )
    else:
        # Plain LoRA without quantization; keep model in float16 if possible
        model = AutoModelForCausalLM.from_pretrained(
            args.model_name,
            torch_dtype=torch.float16 if torch.cuda.is_available() else None,
            device_map="auto",
        )

    # PEFT configuration (applies in both LoRA and QLoRA cases)
    peft_config = LoraConfig(
        r=16,
        lora_alpha=32,
        lora_dropout=0.05,
        bias="none",
        task_type="CAUSAL_LM",
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    )

    # TRL training configuration; these are common settings you may tune.
    sft_config = SFTConfig(
        output_dir=args.output_dir,
        num_train_epochs=args.epochs,
        learning_rate=args.lr,
        per_device_train_batch_size=args.batch_size,
        per_device_eval_batch_size=args.batch_size,
        gradient_accumulation_steps=4,
        logging_steps=10,
        eval_strategy="epoch",
        save_strategy="epoch",
        warmup_ratio=0.1,
        lr_scheduler_type="cosine",
        max_seq_length=512,
        packing=False,
        report_to="none",
    )

    # instantiate trainer
    trainer = SFTTrainer(
        model=model,
        args=sft_config,
        train_dataset=dataset["train"],
        eval_dataset=dataset["validation"],
        peft_config=peft_config,
        processing_class=tokenizer,
        formatting_func=lambda x: x["text"],
    )

    # run training loop
    trainer.train()

    # save final adapter and tokenizer for later inference
    trainer.model.save_pretrained(args.output_dir)
    tokenizer.save_pretrained(args.output_dir)

    print(f"Saved LoRA/QLoRA adapter + tokenizer to {args.output_dir}")


if __name__ == "__main__":
    main()
